## mysql 数据源 配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-cn-north-1-f51a5018ea1d406c.rds.jdcloud.com:3358/jybasic_conf?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&failOverReadOnly=false&allowMultiQueries=true
    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jmq:
    enabled: true
    ####--app producer 定义--##########################################################
    producers:
      basic-producer:
        password: FBBB11B7
        app: JYBasic
        address: jmq-testcluster.jd.local:50088
        enabled: true
      ####--app consumer 定义--##########################################################
    consumers:
      jmq2-consumer:
        password: FBBB11B7
        app: JYBasic
        address: jmq-testcluster.jd.local:50088
        enabled: true
      jmq4-consumer:
        password: 809375866c4842f28d7e4eec04da1e41
        app: JYBasic
        address: test-nameserver.jmq.jd.local:50088
        enabled: true


####--topic 定义--#############################################################
mq:
  topic:
    #叉车完成
    fork-lift-topic: ky_fork_lift_complete
    collectBoxFlowNotice: collect_box_flow_notice
    workGridManagerTaskConfigMq: workGridManagerTaskConfigMq
    workGridModifyMq: workGridModifyMq
    updateUserSchedule: update_user_schedule

  consumer:
    type:
      jyUser: jmq2-consumer
    topic:
      sort_cross_detail: basic_sort_cross_detail
      wlUserInfo: wlUserInfo
      site_change: basic_base_site_change
      wmsSite_Change: basic_ps_storeinfo
      workGridModifyMq: workGridModifyMq
      basic_base_staff_change: basic_base_staff_change

  jmq4producer:
    password: 809375866c4842f28d7e4eec04da1e41
    app: JYBasic
    address: test-nameserver.jmq.jd.local:50088
    enabled: true

  split:
    uat:
      switch: false






## 云redis配置
jimdb:
  url: "redis://:Kktest123456@redis-wjcq8oxg0xjx-proxy-nlb.jvessel-open-hb.jdcloud.com/0"
  cfg:
    timeout: 2000
    newTimeout: 1000
    poolConfig:
      minEvictableIdleTimeMillis: -1
      softMinEvictableIdleTimeMillis: -1
      numTestsPerEvictionRun: -1
      timeBetweenEvictionRunsMillis: 30000
      minIdlePerKey: 0
      maxIdlePerKey: 32
      maxTotalPerKey: 200

#jdq 配置
jdq:
  enabled: false
  producers:
    - id: "colletBoxFlowDirection"
      clientId: "jdq_client_id"
      topic: "jdq_topic"
      password: "jdq_password"
      domain: "jdq_domain"

###### jsf config  start######
  #基础服务JSF别名
jsf:
  jy_basic:
    alias: jy-basic-server-dev
    token: jy-basic-server-token
  sortWorkbenchBusiness:
    alias: sortWorkbenchBusiness-test
    token: sortWorkbenchBusiness-token
  boxFlowRouterVerifyTask:
    alias: boxFlowRouterVerifyTask
  automatic:
    alias: test
    token: automatic
    timeout: 2000
  video:
    channel:
      alias: videoChannelService-jsf-uat-330
      timeout: 3000

basic:
  jsf:
    token: 123456
    alias: basic-ql-jsf
    timeout: 10000

ldop:
  basic:
    jsf:
      alias: ldop-basic-test
      timeout: 10000

###### jsf config  end######
site:
  siteType: 4
  subType: 4
  thirdType: 1

## es config
es:
  basic:
    cluster:
      name: erdtools_newes
      ip: nodes-es-avty5e0cy9-0.jvessel-open-hb.jdcloud.com:9300,nodes-es-avty5e0cy9-1.jvessel-open-hb.jdcloud.com:9300,nodes-es-avty5e0cy9-2.jvessel-open-hb.jdcloud.com:9300
      port: 9300
      user: qltest_es
      password: "#Qltest_newes"
      sleep:
        times: 5000
    ## 索引
    basicSite:
      queryIndexAlias: jy_basic_site
      type: jy_basic_site

## ducc 配置(不同应用请设置不同的application)
laf:
  config:
    manager:
      application: jy-basic-services
      resources[0]:
        name: ducc
        uri: ucc://jdos_jy-basic-services:bfe898e2fb1f48719d85e2fd141c03f2@test.ducc.jd.local/v1/namespace/jy_basic_services/config/default/profiles/test?longPolling=60000&neces
      parameters[0]:
        name: autoListener
        value: true

#flowDirectionFunction 配置
fdf:
  functionMap:
    1:
      - "UNSEAL_CAR_POSITION"
      - "UNLOAD_CAR_POSITION"
    2:
      - "SEND_CAR_POSITION"


