## mysql 数据源 配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-cn-north-1-f51a5018ea1d406c.rds.jdcloud.com:3358/jybasic_conf?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&failOverReadOnly=false&allowMultiQueries=true
    username: testwl
    password: 4x1eSVxcq0816pytgeyQAh1wUS
    #Spring Boot 默认是不注入这些属性值的，需要自己绑定
    #druid 数据源专有配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

    #配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    #如果允许时报错  java.lang.ClassNotFoundException: org.apache.log4j.Priority
    #则导入 log4j 依赖即可，Maven 地址：https://mvnrepository.com/artifact/log4j/log4j
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jmq:
    enabled: true
    ####--app producer 定义--##########################################################
    producers:
      basic-producer:
        password: FBBB11B7
        app: JYBasic
        address: jmq-testcluster.jd.local:50088
        enabled: true
      basic-producer-jmq4:
        password: 809375866c4842f28d7e4eec04da1e41
        app: JYBasic
        address: test-nameserver.jmq.jd.local:50088
        enabled: true
      ####--app consumer 定义--##########################################################
    consumers:
      basic-consumer:
        password: FBBB11B7
        app: JYBasic
        address: jmq-testcluster.jd.local:50088
        enabled: true
      basic-consumer-jmq4:
        password: 809375866c4842f28d7e4eec04da1e41
        app: JYBasic
        address: test-nameserver.jmq.jd.local:50088
        enabled: true


####--topic 定义--#############################################################
mq:
  topic:
    #叉车完成
    fork-lift-topic: ky_fork_lift_complete
    collectBoxFlowNotice: collect_box_flow_notice

  consumer:
    topic:
      sort_cross_detail: basic_sort_cross_detail






mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

## 云redis配置
jimdb:
  url: "redis://:erdTest123@redis-nwdwv9zb0ij7-proxy-nlb.jvessel-open-hb.jdcloud.com:6379/0"
  cfg:
    timeout: 2000
    newTimeout: 1000
    poolConfig:
      minEvictableIdleTimeMillis: -1
      softMinEvictableIdleTimeMillis: -1
      numTestsPerEvictionRun: -1
      timeBetweenEvictionRunsMillis: 30000
      minIdlePerKey: 0
      maxIdlePerKey: 32
      maxTotalPerKey: 200

#jdq 配置
jdq:
  enabled: false
  producers:
    - id: "colletBoxFlowDirection"
      clientId: "jdq_client_id"
      topic: "jdq_topic"
      password: "jdq_password"
      domain: "jdq_domain"

###### jsf config  start######

  #基础服务JSF别名
jsf:
  jy_basic:
    alias: jy-basic-server-dev
    token: jy-basic-server-token

basic:
  jsf:
    token: 123456
    alias: basic-ql-jsf
    timeout: 10000

ldop:
  basic:
    jsf:
      alias: ldop-basic-test
      timeout: 10000

###### jsf config  end######

###### siteType ######
site:
  siteType: 4
  subType: 4
  thirdType: 1
