spring:
  application:
    name: dms-workbench-basic-services
  profiles:
    active: dev

mybatis:
  config-locations: mybatis/mybatis-config.xml
  mapper-locations: mapper/*/*.xml
  type-aliases-package: com.jdl.basic.provider.core.dao.*.*