spring:
  jmq:
    enabled: true
    ####--app producer 定义--##########################################################
    producers:
      basic-producer:
        password: FBBB11B7
        app: JYBasic
        address: jmq-testcluster.jd.local:50088
        enabled: true
      basic-producer-jmq4:
        password: FBBB11B7
        app: JYBasic
        address: test-nameserver.jmq.jd.local:50088
        enabled: true
      ####--app consumer 定义--##########################################################
    consumers:
      basic-consumer:
        password: FBBB11B7
        app: JYBasic
        address: jmq-testcluster.jd.local:50088
        enabled: true
      basic-consumer-jmq4:
        password: FBBB11B7
        app: JYBasic
        address: test-nameserver.jmq.jd.local:50088
        enabled: true
####--topic 定义--#############################################################
mq:
  topic:
    #叉车完成
    fork-lift-topic: ky_fork_lift_complete

  consumer:
    topic:
      sort_cross_detail: basic_sort_cross_detail





